---
# A not so empty hello-world.yml file.

name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: Clone-down
        action: actions/checkout@v3
      - name: my-step
        run: ci/build-app.sh

...
