---
# A not so empty hello-world.yml file.

name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build application
        run: ci/build-app.sh
      - name: Run test
        run: ci/unit-test-app.sh

...
